# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 23:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('statusapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.TextField(verbose_name='object ID')),
                ('user_name', models.CharField(blank=True, max_length=50, verbose_name="user's name")),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name="user's email address")),
                ('user_url', models.URLField(blank=True, verbose_name="user's URL")),
                ('comment', models.TextField(max_length=3000, verbose_name='comment')),
                ('submit_date', models.DateTimeField(db_index=True, default=None, verbose_name='date/time submitted')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP address')),
                ('is_public', models.BooleanField(default=True, help_text='Uncheck this box to make the comment effectively disappear from the site.', verbose_name='is public')),
                ('is_removed', models.BooleanField(default=False, help_text='Check this box if the comment is inappropriate. A "This comment has been removed" message will be displayed instead.', verbose_name='is removed')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_customcomment', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'ordering': ('submit_date',),
                'abstract': False,
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'permissions': [('can_moderate', 'Can moderate comments')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=b'', max_length=256)),
                ('dateStart', models.DateTimeField(verbose_name=b'event start date')),
                ('dateEnd', models.DateTimeField(verbose_name=b'event end date')),
                ('dateUpdated', models.DateTimeField(default=datetime.datetime(2016, 4, 11, 0, 25, 45, 146000), verbose_name=b'event updated date')),
                ('resolvedFlag', models.IntegerField(choices=[(1, b'resolved'), (2, b'outstanding')], default=2)),
                ('status', models.IntegerField(choices=[(1, b'normal'), (2, b'critical')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='customcomment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statusapp.Event'),
        ),
        migrations.AddField(
            model_name='customcomment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='customcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customcomment_comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
