# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 01:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0002_auto_20160411_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='submit_date',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='user_url',
        ),
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 2, 58, 23, 814000), verbose_name=b'event updated date'),
        ),
    ]
