# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0004_auto_20160411_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 3, 6, 28, 283000), verbose_name=b'event updated date'),
        ),
        migrations.AddField(
            model_name='testclass',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statusapp.Event'),
        ),
    ]
