# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 02:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0005_auto_20160411_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 3, 10, 37, 853000), verbose_name=b'event updated date'),
        ),
        migrations.AlterField(
            model_name='testclass',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testclasses', related_query_name=b'testclasses', to='statusapp.Event'),
        ),
    ]
