# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        ('statusapp', '0006_auto_20160411_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentWithTitle',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_comments.Comment')),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('submit_date',),
                'abstract': False,
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'permissions': [('can_moderate', 'Can moderate comments')],
            },
            bases=('django_comments.comment',),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 19, 44, 48, 547000), verbose_name=b'event updated date'),
        ),
    ]
