# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0008_auto_20160411_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 19, 55, 36, 361000), verbose_name=b'event updated date'),
        ),
    ]
