# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        ('statusapp', '0011_auto_20160411_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentwithtitle',
            name='comment_ptr',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='customcomment',
            name='site',
        ),
        migrations.RemoveField(
            model_name='testclass',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 21, 23, 15, 328000), verbose_name=b'event updated date'),
        ),
        migrations.DeleteModel(
            name='CommentWithTitle',
        ),
        migrations.DeleteModel(
            name='CustomComment',
        ),
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
