# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0012_auto_20160411_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 21, 57, 59, 834000), verbose_name=b'event updated date'),
        ),
    ]
