# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0013_auto_20160411_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 22, 3, 10, 276000), verbose_name=b'event updated date'),
        ),
    ]
