# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 23:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0015_auto_20160411_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 0, 21, 29, 460000), verbose_name=b'event updated date'),
        ),
    ]
