# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 23:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0016_auto_20160412_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scheduledFlag',
            field=models.IntegerField(choices=[(1, b'unscheduled'), (2, b'scheduled')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 0, 51, 28, 283000), verbose_name=b'event updated date'),
        ),
    ]
