# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0018_auto_20160412_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 0, 57, 12, 835000), verbose_name=b'event updated date'),
        ),
    ]
