# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 23:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0019_auto_20160412_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 0, 58, 5, 656000), verbose_name=b'event updated date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduledFlag',
            field=models.TextField(choices=[(b'unscheduled', b'unscheduled'), (b'scheduled', b'scheduled')], default=b'unscheduled'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, b'normal'), (2, b'critical')], default=1),
        ),
    ]
