# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0024_auto_20160412_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 2, 15, 26, 487000), verbose_name=b'event updated date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduleFlag',
            field=models.TextField(choices=[(2, b'scheduled'), (1, b'unscheduled')], default=1),
        ),
    ]
