# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 23:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0035_auto_20160413_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 0, 39, 55, 6000), verbose_name=b'event updated date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduleFlag',
            field=models.IntegerField(choices=[(2, b'scheduled'), (1, b'unscheduled')], default=1),
        ),
    ]
