# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0036_auto_20160413_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 4, 23, 42, 947000), verbose_name=b'event updated date'),
        ),
    ]
