# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0037_auto_20160413_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 14, 52, 2, 236000), verbose_name=b'event updated date'),
        ),
    ]
