# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0038_auto_20160413_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 15, 59, 18, 591000), verbose_name=b'event updated date'),
        ),
    ]
