# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 00:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0039_auto_20160413_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 1, 2, 13, 512000), verbose_name=b'event updated date'),
        ),
    ]
